AWSTemplateFormatVersion: 2010-09-09
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: "ipv4"
      Name: "LoadBalancer-mlm"
      Scheme: "internet-facing"
      SecurityGroups: !Ref pubSecurityGroup
      #SubnetMappings: [!Ref ---]
      Subnets: [!Ref PublicSubnet, ]
      Type: "application"
      Tags:
        -
          Key: "name"
          Value: "LoadBalancer-mlm"

  UCPGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 350
      HealthCheckPort: 443
      HealthCheckProtocol: "HTTPS"
      Name: "UCPGrp"
      Port: 443
      Protocol: "HTTPS"
      VpcId: !Ref VPC
      TargetType: instance 
      Targets: 
        -
          Id: !Ref MyEC2Instance1
          Port: 443
        -
          Id: !Ref MyEC2Instance2
          Port: 443
        -
          Id: !Ref MyEC2Instance3
          Port: 443
      Tags:
        -
          Key: "name"
          Value: "UCPGrp-mlm"

  ListenerUCP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
        Type: "forward"
        TargetGroupArn: !Ref UCPGrp
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol : "HTTPS"

  DTRGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 350
      HealthCheckPort: 443
      HealthCheckProtocol: "HTTPS"
      Name: "DTRGrp"
      Port: 80
      Protocol: "HTTPS"
      VpcId: !Ref VPC
      TargetType: instance 
      Targets: 
        -
          Id: !Ref MyEC2Instance5
          Port: 443
      Tags:
        -
          Key: "name"
          Value: "DTRGrp-mlm"

  ListenerUCP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
        Type: "forward"
        TargetGroupArn: !Ref DTRGrp
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol : "HTTPS"

  AppGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 350
      HealthCheckPort: 443
      HealthCheckProtocol: "HTTPS"
      Name: "UCPGrp"
      Port: 8080
      Protocol: "HTTPS"
      VpcId: !Ref VPC
      TargetType: instance 
      Targets: 
        -
          Id: !Ref MyEC2Instance1
          Port: 443
        -
          Id: !Ref MyEC2Instance2
          Port: 443
        -
          Id: !Ref MyEC2Instance3
          Port: 443
        -
          Id: !Ref MyEC2Instance4
          Port: 443
        -
          Id: !Ref MyEC2Instance5
          Port: 443

  ListenerAPP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
        Type: "forward"
        TargetGroupArn: !Ref AppGrp
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol : "HTTPS"

