AWSTemplateFormatVersion: 2010-09-09
Description: Docker cluster root stack
Parameters:
  NetworkStackName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: network

  InstancesStackName:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: instances

Resources:

  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm/network_stacks.yml"
      Tags:
        - Key: Name
          Value: '${NetworkStackName}'

  InstancesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm/instances_stacks.yml"
      Parameters:
        NetworkStackName: '{$AWS::StackName}-${NetworkStackName}'
      Tags:
        - Key: Name
          Value: '${InstancesStackName}'

    DependsOn: NetworkStack 
  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cf-templates-hfix7v22gvfa-us-east-1/template-infra-mlm/loadBalancer_stacks.yml"
      Parameters:
        NetworkStackName: '${$AWS::StackName}-{NetworkStackName}'
        InstancesStackName: '{$AWS::StackName}-${InstancesStackName}'
      Tags:
        - Key: Name
          Value: LoadBalancer-mlm
    DependsOn: InstancesStack 
